[package]
name = "quadriflow-extractor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Quad mesh extraction from parametrization"

[dependencies]
quadriflow-parametrizer = { workspace = true }
pinocchio-math = { workspace = true }
pinocchio-mesh = { workspace = true }
nalgebra = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

[features]
default = ["parallel"]
parallel = []

[dev-dependencies]
approx = { workspace = true }
